--DROP TABLE choices;

CREATE TABLE choices (
    id              BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    question_id     UUID        NOT NULL,
    choice_label    VARCHAR(10) NOT NULL,
    choice_text     TEXT        NOT NULL,
    is_correct      BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_choices
        PRIMARY KEY (id),

    CONSTRAINT fk_choices_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id),

    CONSTRAINT uq_choices_question_id_label
        UNIQUE (question_id, choice_label)
);

CREATE INDEX idx_choices_question_id
    ON choices (question_id);