--DROP TABLE choices;

CREATE TABLE choices (
    id              BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    qid             UUID        NOT NULL,
    choice_label    VARCHAR(10) NOT NULL,
    choice_text     TEXT        NOT NULL,
    is_correct      BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_choices
        PRIMARY KEY (id),

    CONSTRAINT fk_choices_question
        FOREIGN KEY (qid)
        REFERENCES questions(qid),

    CONSTRAINT uq_choices_qid_label
        UNIQUE (qid, choice_label)
);

CREATE INDEX idx_choices_qid
    ON choices (qid);