openapi: 3.0.3

info:
  title: Ruid.ai API
  version: 1.0.0
  description: Ruid.ai API一覧

servers:
  - url: http://localhost:8080

tags:
  - name: Auth
    description: 認証API

  - name: Question
    description: 問題取得API

paths:
  /auth/login:
    $ref: './paths/login.yaml'

  /auth/register:
    $ref: './paths/register.yaml'

  /question:
    $ref: './paths/question.yaml'

components:
  schemas:
    RegisterRequest:
      $ref: './schemas/register-request.yaml'

    LoginRequest:
      $ref: './schemas/login-request.yaml'

    AuthResponse:
      $ref: './schemas/auth-response.yaml'

    User:
      $ref: './schemas/user.yaml'

    QuestionRequest:
      $ref: './schemas/question-request.yaml'

    