/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/question/{qid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 問題取得
         * @description 指定した問題IDに対応する問題を取得します。
         *
         *     - 問題文
         *     - 選択肢
         *     - 解説
         *     を返します。
         *
         *     問題が存在しない場合は404を返します。
         */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 問題作成
         * @description 指定された条件をもとに新しい問題を作成します。
         *
         *     リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。
         *
         *     作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。
         */
        post: operations["postQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        errorResponse: {
            /**
             * @description HTTPステータスコード
             * @example 500
             */
            statusCode: number;
            /**
             * @description エラーコード
             * @example VALIDATION_ERROR
             */
            errorCode: string;
            /**
             * @description ヘッダー（ここでは使わないが、他の正常レスポンスとの共通化をはかる）
             * @example
             */
            headers?: Record<string, never>;
            content: {
                /**
                 * @description エラーメッセージ
                 * @example qidはUUID形式で指定してください。
                 */
                message: string;
            };
        };
    };
    responses: {
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        GetQuestionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        CreateQuestionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 問題を取得しました。 */
        getQuestionResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * @description HTTPステータスコード（200）
                     * @example 200
                     */
                    statusCode: number;
                    /** @description 返却する検索結果 */
                    content: {
                        /**
                         * @description 問題文（Markdown）
                         * @example テスト用問題文
                         *     改行もあるよ
                         *     **how's the bold letter?**
                         */
                        question_text: string;
                        /**
                         * @description 選択肢配列. 選択肢を表す記号と選択肢の本文のセット
                         * @example [
                         *       {
                         *         "tag": "A",
                         *         "text": "choice1"
                         *       },
                         *       {
                         *         "tag": "B",
                         *         "text": "choice2"
                         *       }
                         *     ]
                         */
                        choices: {
                            tag: string;
                            text: string;
                        }[];
                        /**
                         * @description 選択肢の中で、正解のインデックス
                         * @example 1
                         */
                        correct_answer_index: number;
                        /**
                         * @description 解説文（Markdown）
                         * @example ここに説明が表示されるはずです
                         *     **それも、マークダウンで！**
                         */
                        explanation_text: string;
                    };
                };
            };
        };
        /** @description 問題を作成しました。 */
        createQuestionResponse: {
            headers: {
                Location: components["headers"]["location"];
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * @description HTTPステータスコード（200）
                     * @example 200
                     */
                    statusCode: number;
                    /** Format: uuid */
                    qid: string;
                };
            };
        };
        errorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        Qid: string;
        /** @description 問題ID(UUID) */
        qid: string;
    };
    requestBodies: {
        Qprompt: {
            content: {
                "*/*"?: never;
            };
        };
        qprompt: {
            content: {
                "application/json": {
                    prompt: string;
                };
            };
        };
    };
    headers: {
        Location: unknown;
        SetCookie: unknown;
        WWWAuthenticate: unknown;
        /** @description 作成したリソースのURI */
        location: string;
        /** @description Cookieを設定する。 HttpOnly、Secure、SameSite=Laxなどの属性を含む。 */
        "set-cookie": string;
        /** @description 認証方式と認証エラー情報 */
        "www-authenticate": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 問題ID(UUID) */
                qid: components["parameters"]["qid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["getQuestionResponse"];
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description 問題が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
        };
    };
    postQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["qprompt"];
        responses: {
            201: components["responses"]["createQuestionResponse"];
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description 問題が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
        };
    };
}
