/* tslint:disable */
/* eslint-disable */
/**
 * Ruid.ai API
 * Ruid.ai API一覧
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface GetNewQuestionId200Response {
    /**
     * Question ID
     */
    'question_id': string;
}
export interface GetQuestion200Response {
    /**
     * Room ID
     */
    'room_id': string;
    /**
     * 問題文（Markdown）
     */
    'question_text': string;
    /**
     * 選択肢配列. 選択肢を表す記号と選択肢の本文のセット
     */
    'choices': Array<GetQuestion200ResponseChoicesInner>;
    /**
     * 選択肢の中で、正解のインデックス
     */
    'correct_answer_index': number;
    /**
     * 解説文（Markdown）
     */
    'explanation_text': string;
    /**
     * 回答済みフラグ
     */
    'answered_flg': boolean;
    /**
     * 問題の短い説明
     */
    'summary': string;
}
export interface GetQuestion200ResponseChoicesInner {
    'tag': string;
    'text': string;
}
export interface GetQuestion400Response {
    /**
     * エラーコード
     */
    'errorCode': string;
    /**
     * ヘッダー（ここでは使わないが、他の正常レスポンスとの共通化をはかる）
     */
    'headers'?: object;
    'content': GetQuestion400ResponseContent;
}
export interface GetQuestion400ResponseContent {
    /**
     * エラーメッセージ
     */
    'message': string;
}
export interface GetQuestionsByRoomId200ResponseInner {
    /**
     * Question ID
     */
    'question_id': string;
    /**
     * 問題要約
     */
    'summary': string;
}
export interface GetRoom200Response {
    /**
     * ルームの端的な説明＝ルーム名
     */
    'title': string;
}
export interface PostRoom201Response {
    'room_id': string;
}

/**
 * QuestionApi - axios parameter creator
 */
export const QuestionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} questionId パスパラメータ内のquestion_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion: async (questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('getQuestion', 'questionId', questionId)
            const localVarPath = `/questions/{question_id}`
                .replace('{question_id}', encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionApi - functional programming interface
 */
export const QuestionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionApiAxiosParamCreator(configuration)
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} questionId パスパラメータ内のquestion_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestion(questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetQuestion200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestion(questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionApi.getQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionApi - factory interface
 */
export const QuestionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionApiFp(configuration)
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} questionId パスパラメータ内のquestion_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion(questionId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetQuestion200Response> {
            return localVarFp.getQuestion(questionId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestionApi - object-oriented interface
 */
export class QuestionApi extends BaseAPI {
    /**
     * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
     * @summary 問題取得
     * @param {string} questionId パスパラメータ内のquestion_id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestion(questionId: string, options?: RawAxiosRequestConfig) {
        return QuestionApiFp(this.configuration).getQuestion(questionId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RoomApi - axios parameter creator
 */
export const RoomApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ルームIDから、そのルーム内で未回答の問題を取得します。  - 問題ID を返します。  未回答の問題が存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewQuestionId: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('getNewQuestionId', 'roomId', roomId)
            const localVarPath = `/rooms/{room_id}/questions/next`
                .replace('{room_id}', encodeURIComponent(String(roomId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 指定したルームID内の問題リストを取得します。  - 問題要約 - 問題ID を返します。  ルームが存在しない場合は404を返します。 
         * @summary 問題リスト取得
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionsByRoomId: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('getQuestionsByRoomId', 'roomId', roomId)
            const localVarPath = `/rooms/{room_id}/questions`
                .replace('{room_id}', encodeURIComponent(String(roomId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ルームIDから、ルームの情報を取得します。  - ルーム名 を返します。  ルームが存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoom: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('getRoom', 'roomId', roomId)
            const localVarPath = `/rooms/{room_id}`
                .replace('{room_id}', encodeURIComponent(String(roomId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary ルーム作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postRoom: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/rooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomApi - functional programming interface
 */
export const RoomApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomApiAxiosParamCreator(configuration)
    return {
        /**
         * ルームIDから、そのルーム内で未回答の問題を取得します。  - 問題ID を返します。  未回答の問題が存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewQuestionId(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetNewQuestionId200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewQuestionId(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.getNewQuestionId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 指定したルームID内の問題リストを取得します。  - 問題要約 - 問題ID を返します。  ルームが存在しない場合は404を返します。 
         * @summary 問題リスト取得
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestionsByRoomId(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetQuestionsByRoomId200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionsByRoomId(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.getQuestionsByRoomId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ルームIDから、ルームの情報を取得します。  - ルーム名 を返します。  ルームが存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoom(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRoom200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoom(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.getRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary ルーム作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postRoom(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostRoom201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postRoom(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.postRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoomApi - factory interface
 */
export const RoomApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomApiFp(configuration)
    return {
        /**
         * ルームIDから、そのルーム内で未回答の問題を取得します。  - 問題ID を返します。  未回答の問題が存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewQuestionId(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetNewQuestionId200Response> {
            return localVarFp.getNewQuestionId(roomId, options).then((request) => request(axios, basePath));
        },
        /**
         * 指定したルームID内の問題リストを取得します。  - 問題要約 - 問題ID を返します。  ルームが存在しない場合は404を返します。 
         * @summary 問題リスト取得
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestionsByRoomId(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<GetQuestionsByRoomId200ResponseInner>> {
            return localVarFp.getQuestionsByRoomId(roomId, options).then((request) => request(axios, basePath));
        },
        /**
         * ルームIDから、ルームの情報を取得します。  - ルーム名 を返します。  ルームが存在しない場合は404を返します。 
         * @param {string} roomId パスパラメータ内のroom_id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoom(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetRoom200Response> {
            return localVarFp.getRoom(roomId, options).then((request) => request(axios, basePath));
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary ルーム作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postRoom(options?: RawAxiosRequestConfig): AxiosPromise<PostRoom201Response> {
            return localVarFp.postRoom(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomApi - object-oriented interface
 */
export class RoomApi extends BaseAPI {
    /**
     * ルームIDから、そのルーム内で未回答の問題を取得します。  - 問題ID を返します。  未回答の問題が存在しない場合は404を返します。 
     * @param {string} roomId パスパラメータ内のroom_id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNewQuestionId(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).getNewQuestionId(roomId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 指定したルームID内の問題リストを取得します。  - 問題要約 - 問題ID を返します。  ルームが存在しない場合は404を返します。 
     * @summary 問題リスト取得
     * @param {string} roomId パスパラメータ内のroom_id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestionsByRoomId(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).getQuestionsByRoomId(roomId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ルームIDから、ルームの情報を取得します。  - ルーム名 を返します。  ルームが存在しない場合は404を返します。 
     * @param {string} roomId パスパラメータ内のroom_id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoom(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).getRoom(roomId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
     * @summary ルーム作成
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public postRoom(options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).postRoom(options).then((request) => request(this.axios, this.basePath));
    }
}



