/* tslint:disable */
/* eslint-disable */
/**
 * Ruid.ai API
 * Ruid.ai API一覧
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ErrorResponse {
    /**
     * HTTPステータスコード
     */
    'statusCode': number;
    /**
     * エラーコード
     */
    'errorCode': string;
    /**
     * ヘッダー（ここでは使わないが、他の正常レスポンスとの共通化をはかる）
     */
    'headers'?: object;
    'content': ErrorResponseContent;
}
export interface ErrorResponseContent {
    /**
     * エラーメッセージ
     */
    'message': string;
}
export interface GetQuestion200Response {
    /**
     * HTTPステータスコード（200）
     */
    'statusCode': number;
    'content': GetQuestion200ResponseContent;
}
/**
 * 返却する検索結果
 */
export interface GetQuestion200ResponseContent {
    /**
     * 問題文（Markdown）
     */
    'question_text': string;
    /**
     * 選択肢配列. 選択肢を表す記号と選択肢の本文のセット
     */
    'choices': Array<GetQuestion200ResponseContentChoicesInner>;
    /**
     * 選択肢の中で、正解のインデックス
     */
    'correct_answer_index': number;
    /**
     * 解説文（Markdown）
     */
    'explanation_text': string;
}
export interface GetQuestion200ResponseContentChoicesInner {
    'tag': string;
    'text': string;
}
export interface PostQuestion201Response {
    /**
     * HTTPステータスコード（200）
     */
    'statusCode': number;
    'qid': string;
}

/**
 * QuestionApi - axios parameter creator
 */
export const QuestionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} qid 問題ID(UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion: async (qid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'qid' is not null or undefined
            assertParamExists('getQuestion', 'qid', qid)
            const localVarPath = `/question/{qid}`
                .replace('{qid}', encodeURIComponent(String(qid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary 問題作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postQuestion: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/question`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionApi - functional programming interface
 */
export const QuestionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionApiAxiosParamCreator(configuration)
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} qid 問題ID(UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getQuestion(qid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetQuestion200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestion(qid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionApi.getQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary 問題作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postQuestion(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostQuestion201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postQuestion(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionApi.postQuestion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionApi - factory interface
 */
export const QuestionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionApiFp(configuration)
    return {
        /**
         * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
         * @summary 問題取得
         * @param {string} qid 問題ID(UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getQuestion(qid: string, options?: RawAxiosRequestConfig): AxiosPromise<GetQuestion200Response> {
            return localVarFp.getQuestion(qid, options).then((request) => request(axios, basePath));
        },
        /**
         * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
         * @summary 問題作成
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postQuestion(options?: RawAxiosRequestConfig): AxiosPromise<PostQuestion201Response> {
            return localVarFp.postQuestion(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestionApi - object-oriented interface
 */
export class QuestionApi extends BaseAPI {
    /**
     * 指定した問題IDに対応する問題を取得します。  - 問題文 - 選択肢 - 解説 を返します。  問題が存在しない場合は404を返します。 
     * @summary 問題取得
     * @param {string} qid 問題ID(UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getQuestion(qid: string, options?: RawAxiosRequestConfig) {
        return QuestionApiFp(this.configuration).getQuestion(qid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 指定された条件をもとに新しい問題を作成します。  リクエストボディには、問題ジャンルや問題形式などの生成条件を指定します。  作成に成功した場合は201 Createdを返し、Locationヘッダーに作成した問題のリソースURIを設定します。 
     * @summary 問題作成
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public postQuestion(options?: RawAxiosRequestConfig) {
        return QuestionApiFp(this.configuration).postQuestion(options).then((request) => request(this.axios, this.basePath));
    }
}



